# Generated by Django 5.0.7 on 2024-08-10 17:44

import django.db.models.deletion
import phone_field.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('FF', 'Fundacja'), ('OP', 'Organizacja Pozarządowa'), ('ZL', 'Zbiórka Lokalna')], default='FF', max_length=2)),
                ('categories', models.ManyToManyField(to='Oddam_w_dobre_ręce_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('address', models.CharField()),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('city', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=5)),
                ('pick_up_date', models.DateField(auto_now_add=True)),
                ('pick_up_time', models.TimeField(auto_now_add=True)),
                ('pick_up_comment', models.TextField()),
                ('categories', models.ManyToManyField(to='Oddam_w_dobre_ręce_app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oddam_w_dobre_ręce_app.institution')),
            ],
        ),
    ]
